safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Maxgrok"
description: "A blog dedicated to maxgrok progress learning full-stack web application development!"
baseurl: "maxgrok.github.io"
url: "maxgrok.github.io" # replace by your site's url
twitter_username: your-name
github_username:  maxgrok # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Maxgrok"
address: "Your Street, <br>Your City, Country"
email: "maxgrok2011@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
